"""
Task 1 Bonus - Equity Research Brief Renderer
CDAZZDEV Senior MLE Assessment

Combines Task 1A + 1B outputs into a one-page Markdown/HTML report with
an embedded matplotlib chart and a mandatory risk disclaimer.

# AI-ASSISTED: Claude (claude-sonnet-4-5), Prompt: 'render a styled HTML
# equity research brief with an embedded base64 matplotlib chart',
# Date: 2026-09-10
"""

from __future__ import annotations

import base64
import io
from datetime import datetime, timezone

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

DISCLAIMER = (
    "**Disclaimer:** This report is generated by an automated research assistant for "
    "educational and demonstration purposes only. It does not constitute investment advice. "
    "Past performance and model-generated signals are not indicative of future results. "
    "Consult a licensed financial advisor before making investment decisions."
)


def _price_chart_base64(df) -> str:
    fig, ax = plt.subplots(figsize=(8, 3.5))
    ax.plot(df.index, df["close"], label="Close", linewidth=1.2)
    ax.plot(df.index, df["sma_50"], label="SMA 50", linewidth=1)
    ax.plot(df.index, df["sma_200"], label="SMA 200", linewidth=1)
    ax.fill_between(df.index, df["bb_lower"], df["bb_upper"], alpha=0.12, label="Bollinger Band")
    ax.set_title("Price, Moving Averages & Bollinger Bands")
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=120)
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode("utf-8")


def render_markdown(pipeline_out: dict, reasoning_out: dict) -> str:
    s = pipeline_out["summary"]
    sentiment = reasoning_out["sentiment"]
    signal = reasoning_out["signal"] or {"signal": "N/A", "justification": "Signal generation failed validation."}
    top_headlines = sentiment["per_headline"][:3]

    md = f"""# Equity Research Brief - {s['ticker']}
*Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*

## Company Snapshot
| Metric | Value |
|---|---|
| Current Price | {s['current_price']} |
| 52-Week High | {s['week52_high']} |
| 52-Week Low | {s['week52_low']} |
| P/E Ratio | {s['pe_ratio']} |
| YTD Return | {s['ytd_return_pct']}% |

## Technical Outlook
Momentum signal from indicators: **{s['momentum_signal']}**

## News Sentiment Summary
Overall sentiment score (-1 to 1): **{sentiment['overall_sentiment_score']}** \
({sentiment['n_scored']} headlines scored, {sentiment['n_failed']} failed validation)

**Top headlines:**
"""
    for h in top_headlines:
        md += f"- *{h['headline']}* — {h['sentiment']} (confidence {h['confidence']:.2f}): {h['brief_reason']}\n"

    md += f"""
## LLM Recommendation
**Signal: {signal['signal']}**

{signal['justification']}

---
{DISCLAIMER}
"""
    return md


def render_html(pipeline_out: dict, reasoning_out: dict) -> str:
    md_report = render_markdown(pipeline_out, reasoning_out)
    chart_b64 = _price_chart_base64(pipeline_out["ohlcv_with_indicators"])

    try:
        import markdown as md_lib
        body_html = md_lib.markdown(md_report, extensions=["tables"])
    except ImportError:
        body_html = f"<pre>{md_report}</pre>"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Equity Research Brief - {pipeline_out['summary']['ticker']}</title>
<style>
 body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; }}
 table {{ border-collapse: collapse; width: 100%; }}
 th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; }}
 img {{ max-width: 100%; border: 1px solid #eee; border-radius: 6px; }}
 .disclaimer {{ font-size: 0.85em; color: #666; border-top: 1px solid #ddd; padding-top: 10px; margin-top: 20px; }}
</style></head><body>
{body_html}
<img src="data:image/png;base64,{chart_b64}" alt="Price chart" />
</body></html>"""


if __name__ == "__main__":
    from data_pipeline import run_pipeline
    from llm_reasoning import run_reasoning

    p_out = run_pipeline("AAPL")
    r_out = run_reasoning(p_out)
    html = render_html(p_out, r_out)
    with open("equity_brief.html", "w", encoding="utf-8") as f:
        f.write(html)
    print("Saved equity_brief.html")
